jobs/ci_open_jenkins/build/cb.groovy
=> adding monitor and jenkins job for cb-frontend

jobs/ci_open_jenkins/build/tavc.groovy
Updated to include investment-tax-relief-subscription frontend and Microservice.
Monitors also updated.
=> TAVC-792 updated Jenkins Jobs for TAVC- subscription service

jobs/ci_open_jenkins/build/tavc.groovy
jobs/ci_open_jenkins/build/tavc.groovy
=> TAVC-803 added dynamic stubs to tavc.groovy

jobs/ci_open_jenkins/build/tavc.groovy
jobs/ci_open_jenkins/build/tavc.groovy
./gradlew test  = successful
=> TAVC-870 updated tavc.groovy to include new agent frontend

jobs/ci_open_jenkins/build/tavc.groovy
Added entry to tavc.groovy file under ci_open_jenkins/build for:
investment-tax-relief-agent (microservice)
investment-tax-relief-agent-dynamic-stub (stub)
=> TAVC-912 Add microservice and dynamic stub entries for Agent service

jobs/ci_open_jenkins/build/cb.groovy
=> adding build and monitor for birth-registration-matching

jobs/ci_open_jenkins/build/csr.groovy
Add Civil Service Resourcing jobs
=> Add CSR fasttrack front-end and service

jobs/ci_open_jenkins/build/cb.groovy
@adamconder  
Added birth-registration-matching-proxy service
=> Added birth-registration-matching-proxy service

jobs/ci_open_jenkins/build/ated.groovy
=> ated.groovy added

jobs/ci_open_jenkins/build/ated.groovy
=> ated monitor updated

jobs/ci_open_jenkins/build/childcare-calculator.groovy
Please review and let me know comments
=> CCALC-2182 - addedjob to build cc-frontend-qa

jobs/ci_open_jenkins/build/awrs.groovy
=> Added awrs-notification

jobs/ci_open_jenkins/build/awrs.groovy
=> use SbtMicroserviceJobBuilder

jobs/ci_open_jenkins/build/bbsi.groovy
=> TAI-1550: Created groovy for bbsi microservices build

jobs/ci_open_jenkins/build/awrs.groovy
add withTests to awrs notification config
=> add withTests to awrs notification config

jobs/ci_open_jenkins/build/new-childcare-schemes.groovy
@shridhaarchippaa Please review and let me know if any comments.
=> added new groovy files

jobs/ci_open_jenkins/build/pdf-generator-frontend.groovy
A test harness for the pdf-generator-service
=> added pdf-generator-frontend

jobs/ci_open_jenkins/build/pdf-generator-frontend.groovy
corrected the imports in pdf-generator-frontend.groovy
=> OFFPAY-95: corrected entry for pdf-generator-frontend

jobs/ci_open_jenkins/build/ngc.groovy
and hangs his head in shame :|
=> Add missing imports

src/main/groovy/uk/gov/hmrc/jenkinsjobs/domain/step/Steps.groovy
The command universal:publish has been added which will create & publish a zip & tgz
=> Add universal commands to step sbtCleanTestFullOptJsPublish

jobs/ci_open_jenkins/build/apprenticeship-levy.groovy
Configured apprenticeship-levy api build to run integration tests, coverage and scala style.
=> DDCNLS-410: Retired apprenticeship-levy-stub and employment check.

jobs/ci_open_jenkins/build/sabr.groovy
@MJCallahanPage - please review changes.
=> SAR-91 - Updated SABR groovy file with frontend changes

jobs/ci_open_jenkins/build/eeitt.groovy
This is making the build fail, for reasons not yet clear, let's get it building first
=> Removed style check and coverage

jobs/ci_open_jenkins/build/ras.groovy
@raghu1978 Could you review this and merge in if acceptable.
=> RAS-98 | Adding job builder and build monitor for ras

jobs/ci_open_jenkins/build/lisa.groovy
=> Added lisa-frontend

jobs/ci_open_jenkins/build/lisa.groovy
Added reference to frontendjobbuilder
=> Updated lisa.groovy

jobs/ci_open_jenkins/build/awrs.groovy
[AWRS-1898] - add feedback-survey-frontend config
=> [AWRS-1898] - add feedback-survey-frontend config

jobs/ci_open_jenkins/build/apiservices.groovy
Rename the deployment-approval-frontend service to api-service-approval-frontend
=> APIS-1724 Rename deployment-approval-service

jobs/ci_open_jenkins/build/nisp.groovy
NISP-2371: Decomissioning NISP
=> NISP-2371: Decomissioning NISP

jobs/ci_open_jenkins/build/customer.groovy
=> RAS-287 | refactored service name from customer to customer-api

src/main/groovy/uk/gov/hmrc/jenkinsjobs/domain/variable/JavaVersionEnvironmentVariable.groovy
=> Revert "PLATOPS-1001 - update the java version to 1.8.0-131"

jobs/ci_open_jenkins/build/auth.groovy
=> Revert "Making auth builds trigger every day."

jobs/ci_open_jenkins/build/pla-api.groovy
@nkaraolis can you review and merge please.
=> Adding the pensions-lifetime-allowance-des-stub per ticket (PLA-1556)

jobs/ci_open_jenkins/build/off-payroll.groovy
gradle tests successfully run locally
`Brians-MacBook-Pro:jenkins-jobs brianheathcote$ ./gradlew clean test
:clean
:compileJava UP-TO-DATE
:compileGroovy
:processResources UP-TO-DATE
:classes
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources UP-TO-DATE
:testClasses
:test
BUILD SUCCESSFUL
Total time: 11.767 secs`
=> added off-payroll-analytics-frontend

jobs/ci_open_jenkins/build/agents.groovy
=> [FD][APB-1032] Replace agent-account-frontend with agent-services-account-frontend

jobs/ci_open_jenkins/build/ats.groovy
=> [TAXS-596] - Update ATS groovy config

jobs/ci_open_jenkins/build/scrs.groovy
This reverts commit 67b2414290f01dd2ca81d4e0af1810d19df6f2a0.
=> Revert "Removed ScalaStyle from job for now"

jobs/ci_open_jenkins/build/platform-services.groovy
=> PLATY-216 Created file for Platform Services, added contact-admin service

jobs/ci_open_jenkins/build/mtd.groovy, src/main/groovy/uk/gov/hmrc/jenkinsjobs/domain/builder/JourneyTestsWithZapJobBuilder.groovy, src/main/groovy/uk/gov/hmrc/jenkinsjobs/domain/builder/ZapTestsFollowingJourneyJobBuilder.groovy, src/test/groovy/uk/gov/hmrc/jenkinsjobs/domain/builder/JourneyTestsWithZapJobBuilderSpec.groovy, src/test/groovy/uk/gov/hmrc/jenkinsjobs/domain/builder/ZapTestsFollowingJourneyJobBuilderSpec.groovy
as their start and test command
=> PBD-330 Rework Zap classes to accept only a single shell step 

jobs/ci_open_jenkins/build/ngc.groovy
+ add native-app-widget to NGC-MONITOR, this was probably forgotten when the service job was added.
=> NGC-2634 Add mobile-help-to-save

jobs/ci_open_jenkins/build/ngc.groovy
Note: `BuildMonitorViewBuilder('NGC-MONITOR')` changes are whitespace-only.
=> NGC-2634 scoverage report for mobile-help-to-save

jobs/ci_open_jenkins/build/nonrep.groovy
Added nonrep retrieval and retrieval frontend.
=> Added job for nrs retrieval and nrs retrieval frontend.

jobs/ci_open_jenkins/build/employment-expenses-tax-relief-guidance-frontend.groovy
New build job for building frontend service and build monitor
=> Adding new service build jobs

jobs/ci_open_jenkins/build/sdil.groovy
=> adding SDIL returns FE

jobs/ci_open_jenkins/build/ddcn-live-service.groovy
DDCNLS-2610 : Decomissioning CSI
=> DDCNLS-2610 : Decomissioning CSI

src/main/groovy/uk/gov/hmrc/jenkinsjobs/domain/builder/NpmLibraryJobBuilder.groovy
I have run 'clean test' and confirmed there are no issues.
=> PBD-121 Adding credential binding needed for publishing to the public NPM registry

src/main/groovy/uk/gov/hmrc/jenkinsjobs/domain/variable/JavaVersionEnvironmentVariable.groovy
=> upgrading java version to 172

jobs/ci_open_jenkins/build/nonrepudiation.groovy
Temporarily remove scoverage from nrs-retrieval.
=> [NONPR-716] Add "Back" link to Choose digital submission and Search pages

jobs/ci_open_jenkins/build/ngc.groovy
It's moving to new build: https://github.com/hmrc/build-jobs/pull/49
=> [NGC-3674][FD] Remove mobile-user-contact

jobs/ci_open_jenkins/build/ngc.groovy
=> [NGC-3674][FD] Remove mobile-help-to-save and -frontend

jobs/ci_open_jenkins/build/apiplatform.groovy
=> APIS-MIGRATE

jobs/ci_open_jenkins/build/epaye.groovy
Adding new groovy file as part of checklist for epaye-frontend, epaye and epaye-api plus monitoring for all three services
=> DL-1211 adding groovy file for epaye

jobs/ci_open_jenkins/build/agents.groovy
[APB-2947][AO] remove agent-fi-relationship from ci-open jenkins
=> [APB-2947][AO] remove agent-client-relationships from ci-open jenkins

jobs/ci_open_jenkins/build/ddcn-live-service.groovy
remove pbik from build monitor
=> DDCNLS-5089: Remove pbik jobs
